#!/usr/bin/env bash
# This script displays username, user id and home directory from /etc/passwd

while IFS=':' read -r username x userid x x homedir x
do
    echo "$username:$userid:$homedir"
done < "/etc/passwd"
