#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code from Apache log file
# and displays the data ordered by occurrence number

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn | awk '{ print $1 " " $2 " " $3 }'
