#!/usr/bin/env bash
# Init script to manage manage_my_process

PIDFILE="/var/run/my_process.pid"

start_process() {
    ./manage_my_process &
    echo "$!" > "$PIDFILE"
    if [ "$1" != "restart" ]; then
        echo "manage_my_process started"
    fi
}

stop_process() {
    if [ -e "$PIDFILE" ]; then
        pid=$(cat "$PIDFILE")
        kill "$pid"
        rm "$PIDFILE"
    fi
    if [ "$1" != "restart" ]; then
        echo "manage_my_process stopped"
    fi
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        stop_process "restart"
        start_process "restart"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac